### ISSUE TITLE
Please provide updated Thunderbolt NVM (26) on LVFS for XPS 9350

### ISSUE THREAD

**Issue by ssledz** [dell/thunderbolt-nvm-linux#21] opened 2019-05-20 00:00 UTC
The Thunderbolt NVM on LVFS has version 16, but on the Dell website the latest version is 26

https://www.dell.com/support/home/uk/en/ukdhs1/drivers/driversdetails?driverid=fjjk7&oscode=wt64a&productcode=xps-13-9350-laptop

Please provide the updated version on LVFS as well. Thanks!

**Comment by superm1** [comment] 2019-05-20 19:13
It's not obvious; but this is a duplicate of #12 (they're distributed together)

**Closed as completed by superm1** 2019-05-20 19:13 UTC
Labels: duplicate, missing-firmware

**Comment by ssledz** [comment] 2019-05-20 20:24
I have already solved this using the script below
```
cd ~/Downloads/
wget https://downloads.dell.com/FOLDER04795516M/1/Intel_TBT3_FW_UPDATE_NVM26_FJJK7_A08_4.26.11.001.exe
cd ~/git/fwupd/contrib/firmware-packager
./firmware-packager \
  --developer-name "Dell Inc." \
  --firmware-name "Thunderbolt NVM for Xps Notebook 9350 Device Update" \
  --device-guid dbbe0ed9-df91-529c-ac86-8976b78f726d \
  --release-version 26.11 \
  --exe ~/Downloads/Intel_TBT3_FW_UPDATE_NVM26_FJJK7_A08_4.26.11.001.exe \
  --bin Intel/0x0704_secure.bin \
  --out ~/Downloads/firmware.cab
```

```
cd ~/Downloads/ 
fwupdmgr install firmware.cab
```

**Comment by pauloxnet** [comment] 2019-10-24 09:25
In Ubuntu 19.10 I installed these required packages:

```
$ sudo apt install fwupd p7zip-full gcab
```
And then I followed the steps reported by @ssledz as using `/usr/share/fwupd/firmware-packager` as binary to package the firmware.

P.S. @ssledz a `b` is missing at the end of your multi-line instruction

**Comment by ssledz** [comment] 2020-03-24 16:30
Fixed thx @pauloxnet
